### ISSUE TITLE
[Feature/PR Req] Subclass

### ISSUE THREAD

**Issue by jarednova** [nclud/wp-timber-cli#1]
Hey @ramsaylanier! I gave the CLI a try this weekend and I love it! Here's something I'm thinking of for the next go.

One of the things we often do is create a subclass for a project for `TimberPost`, `TimberTerm`, etc. where custom methods can live. Normally we load these into the `lib` directory in the theme. 

So for the syntax...

`wp-timber --subclass post MyPostClass`, or a shortcut of `wp-timber -s post MyPostClass`

WPTCLI would create a file called `lib/MyPostClass.php` and fill it with boilerplate so it extends `TimberPost` and then have the file autoloaded by the theme. The same could be done with site, term, menu, menuitem and user.

If this sounds good to you I could start working on this later this week. Lemme know!

**Comment by ramsaylanier** [comment]
That sounds pretty useful. Go for it! If you submit a PR sometime this week I can probably get to it within a few days.

**Comment by ramsaylanier** [comment]
@jarednova Take a look at the PR that I just merged from @lggorman - is this what you were asking for? If so - I'll close this issue.

**Comment by jarednova** [comment]
Yep! @lggorman works with me at @upstatement — she signed-up for this one and has a tendency to rock it
