### ISSUE TITLE
Command not found: wp-timber

### ISSUE THREAD

**Issue by adamk22** [nclud/wp-timber-cli#5]
I npm installed the tool into my timber theme directory but whenever I try to initiate the command, my command line displays an 

```
$ wp-timber zsh: 
command not found: wp-timber error.
```

Are there any other requirements that I am missing here other than the Timber theme?

**Comment by ramsaylanier** [comment]
where are you getting `zsh:` from? What command were you trying to run?

**Comment by adamk22** [comment]
I'm using http://ohmyz.sh/ as my terminal. But I got it fixed by installing it globally with `npm install -g wp-timber-cli`
